
name: GitHub Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  #schedule:
  #  - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'env to deploy to'
        type: environment
        required: true
  repository_dispatch:
    types: [opened, deleted]

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }}"

      #- uses: actions/checkout@v3.3.0
      #- run: echo '${{ toJSON(runner) }}' 
      - run: echo '${{ toJSON(github) }}' 

      #- name: list files in the repo
      #  run: |
      #    echo "The repository ${{ github.repository }} contains the following files:"
      #    tree
  
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 5

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 2
      - run: |
          echo "🚀 Step 2..."
          sleep 2
      - run: |
          echo "🚀 Step 3..."
          sleep 2
      - run: |
          echo "🚀 Step 4..."
          sleep 2
      - run: |
          echo "🚀 Step 5..."
          sleep 2




      
