
name: GitHub Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  repository_dispatch:
    types: [opened, deleted]

jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      #— name: Dump runner context 
      #- run: echo '${{ toJSON(runner) }}' 
      #— name: Dump GitHub Context
      #- run: echo '${{ toJSON(github) }}' 

      - name: list files in the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
