name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with: 
      who-to-greet: '@octocat'

  use-output:
    #name: call a reusable workflow
    needs: [call-workflow]
    runs-on: ubuntu-latest
    steps:
      #- name: output time to console
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
